module.exports = {
  "ID": 2,
  "name": "Main Menu",
  "slug": "main-menu",
  "description": "",
  "count": 5,
  "items": [{
    "id": 25,
    "order": 1,
    "parent": 0,
    "title": "Home",
    "url": "http:\/\/www.example.dev\/",
    "attr": "",
    "target": "",
    "classes": "",
    "xfn": "",
    "description": "",
    "object_id": 23,
    "object": "page",
    "type": "post_type",
    "type_label": "Page"
  }, {
    "id": 21,
    "order": 2,
    "parent": 0,
    "title": "About",
    "url": "http:\/\/www.example.dev\/about\/",
    "attr": "",
    "target": "",
    "classes": "",
    "xfn": "",
    "description": "",
    "object_id": 4,
    "object": "page",
    "type": "post_type",
    "type_label": "Page"
  }, {
    "id": 26,
    "order": 3,
    "parent": 0,
    "title": "Sample",
    "url": "http:\/\/www.example.dev\/sample-page\/",
    "attr": "",
    "target": "",
    "classes": "",
    "xfn": "",
    "description": "",
    "object_id": 2,
    "object": "page",
    "type": "post_type",
    "type_label": "Page"
  }, {
    "id": 32,
    "order": 4,
    "parent": 0,
    "title": "Blog",
    "url": "http:\/\/www.example.dev\/blog\/",
    "attr": "",
    "target": "",
    "classes": "",
    "xfn": "",
    "description": "",
    "object_id": 30,
    "object": "page",
    "type": "post_type",
    "type_label": "Page"
  }, {
    "id": 33,
    "order": 5,
    "parent": 0,
    "title": "Hello",
    "url": "http:\/\/www.example.dev\/hello-world\/",
    "attr": "",
    "target": "",
    "classes": "",
    "xfn": "",
    "description": "",
    "object_id": 1,
    "object": "post",
    "type": "post_type",
    "type_label": "Post"
  }],
  "meta": {
    "links": {
      "collection": "http:\/\/www.example.dev\/wp-json\/wp\/v2\/menus\/",
      "self": "http:\/\/www.example.dev\/wp-json\/wp\/v2\/menus\/2"
    }
  }
}
